#!/bin/python3

import os
import sys

#
# Complete the handshake function below.
#
def handshake(n):
    if n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        ans = 0
        for i in range(1, n):
            ans += i
        return ans

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        result = handshake(n)

        fptr.write(str(result) + '\n')

    fptr.close()
