#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter
# Complete the checkMagazine function below.
def checkMagazine(magazine, note):
    mag = Counter(magazine)
    nte = Counter(note)
    
    s = set(note)
    for i in s:
        if nte[i] > mag[i]:
            return "No"
    return "Yes"        
    
    

if __name__ == '__main__':
    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    magazine = input().rstrip().split()

    note = input().rstrip().split()

    print(checkMagazine(magazine, note))
