#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter
# Complete the substrCount function below.
def substrCount(n, s):
    c = 0
    val = []
    cur = ""
    for i in range(n):
        if s[i] == cur:
            c += 1
        else:
            if cur is not "":
                val.append((cur, c))
            cur = s[i]
            c = 1
    val.append((cur, c))
    
    ans = 0
    for i in val:
        ans += i[1]*(i[1]+1) // 2
    
    for i in range(1, len(val) - 1):
        if val[i - 1][0] == val[i + 1][0] and val[i][1] == 1:
            ans += min(val[i - 1][1], val[i + 1][1])

    return ans
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = substrCount(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
